name: PR jobs
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}
    strategy:
      # Matrix strategy allows us to run the same job on multiple versions of Node and OSs.
      # Add to it if you need to.
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        run: yarn build
  lint:
    name: Lint on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint
        run: yarn lint