name: PR jobs
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build
        run: yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint
        run: yarn lint